- name: set up filebeat agent config
  k8s:
    api_version: v1
    kind: ConfigMap
    resource_definition:
      metadata:
        name: filebeat-config
        namespace: kube-system
        labels:
          k8s-app: filebeat
      data:
        filebeat.yml: |-
          filebeat.config:
            inputs:
              # Mounted `filebeat-inputs` configmap:
              path: ${path.config}/inputs.d/*.yml
              # Reload inputs configs as they change:
              reload.enabled: false
            modules:
              path: ${path.config}/modules.d/*.yml
              # Reload module configs as they change:
              reload.enabled: false
          processors:
            - add_cloud_metadata:
          output.elasticsearch:
            hosts: ['http://es-master.{{ k8ses_namespace }}.svc.cluster.local:9200']


- name: set up filebeat inputs config
  k8s:
    api_version: v1
    kind: ConfigMap
    resource_definition:
      metadata:
        name: filebeat-inputs
        namespace: kube-system
        labels:
          k8s-app: filebeat
      data:
        kubernetes.yml: |-
          - type: docker
            json.keys_under_root: false
            json.add_error_key: false
            json.ignore_decoding_error: true
            containers.ids:
              - "*"
            processors:
              - add_kubernetes_metadata:
                  in_cluster: true


- name: set up filebeat inputs
  k8s:
    resource_definition: "{{ lookup('template', 'templates/filebeat_inputs.yml.j2') }}"

- name: bind filebeat service account to its matching role
  k8s:
    api_version: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
    resource_definition:
      metadata:
        name: filebeat
      subjects:
      - kind: ServiceAccount
        name: filebeat
        namespace: kube-system
      roleRef:
        kind: ClusterRole
        name: filebeat
        apiGroup: rbac.authorization.k8s.io

- name: create role
  k8s:
    api_version: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRole
    resource_definition:
      metadata:
        name: filebeat
        labels:
          k8s-app: filebeat
      rules:
      - apiGroups: [""] # "" indicates the core API group
        resources:
        - namespaces
        - pods
        verbs:
        - get
        - watch
        - list

- name: create account
  k8s:
    api_version: v1
    kind: ServiceAccount
    resource_definition:
      metadata:
        name: filebeat
        namespace: kube-system
        labels:
          k8s-app: filebeat
