- name: set up filebeat agent config
  k8s:
    api_version: v1
    kind: ConfigMap
    resource_definition:
      metadata:
        name: filebeat-config
        namespace: kube-system
        labels:
          k8s-app: filebeat
      data: "{{ k8ses_filebeat_agent_config }}"

- name: set up filebeat inputs config
  k8s:
    api_version: v1
    kind: ConfigMap
    resource_definition:
      metadata:
        name: filebeat-inputs
        namespace: kube-system
        labels:
          k8s-app: filebeat
      data:
        kubernetes.yml: "{{ k8ses_filebeat_agent_inputs_config }}"

- name: set up filebeat inputs
  k8s:
    src: "{{ lookup('template', 'templates/filebeat_inputs.yml.j2') }}"

- name: bind filebeat service account to its matching role
  k8s:
    api_version: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
    resource_definition:
      metadata:
        name: filebeat
      subjects:
      - kind: ServiceAccount
        name: filebeat
        namespace: kube-system
      roleRef:
        kind: ClusterRole
        name: filebeat
        apiGroup: rbac.authorization.k8s.io

- name: create role
  k8s:
    api_version: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRole
    resource_definition:
      metadata:
        name: filebeat
        labels:
          k8s-app: filebeat
      rules:
      - apiGroups: [""] # "" indicates the core API group
        resources:
        - namespaces
        - pods
        verbs:
        - get
        - watch
        - list

- name: create account
  api_version: v1
  kind: ServiceAccount
  resource_definition:
    metadata:
      name: filebeat
      namespace: kube-system
      labels:
        k8s-app: filebeat
